version: '3.8'

services:
  # FastAPI Application
  orders-api:
    image: tombraudo/cart-service:latest
    container_name: cart-service
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=info
      - RABBITMQ_URL=amqp://guest:guest@host.docker.internal:5672/
    networks:
      - orders-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  orders-network:
    driver: bridge